### PR TITLE
Add storage-java to community client libraries.

### PR DESCRIPTION
**Pull request by MagnusHJensen**
I've spent the past 2 days working on a storage api client in Java. https://github.com/magnushjensen/storage-java 
I would say it's at a usable state for a community repo. 
It has basically 100% test coverage, (inspired from storage-js). 
It has build&test workflows for push and PR's, alongside publishing javadoc to `javadoc` branch. It contains an example.
It also has dependabot enabled.
It just needs some more JavaDocs, which I'm currently working on atm.

This is my request to hopefully contribute and possibly transfer the repository to you guys! :D

### CODE REVIEW

**Comment by thorwebdev** [comment]
Oh awesome, thanks @MagnusHJensen 💚  would you be able to transfer the repo to myself @thorwebdev? I can then transfer it to the `supabase-community` org and add you as a maintainer 🙌

**Comment by MagnusHJensen** [comment]
Hi @thorwebdev .

I have requested a repository transfer to your account!

Cheers.

**Comment by thorwebdev** [comment]
@MagnusHJensen very sorry, I’m travelling atm and missed to action the transfer before it expired. Could you please transfer it to @kiwicopple instead please?

**Comment by MagnusHJensen** [comment]
Hi @thorwebdev 
All good, I aborted the transfer request to you, and sent a new one to @kiwicopple

**Comment by MagnusHJensen** [comment]
Closing this PR as the repo is now under the supbase-community org.

**Pull request closed without merging**
